### ISSUE TITLE
go言語のスケルトンプロジェクトを作りました

### ISSUE THREAD

**Issue by sue445** [tddbc/organizers#18]
[gospel](https://github.com/tddbc/go_gospel) や [ginkgo](https://github.com/tddbc/go_ginkgo) のように特定のテスティングフレームワークのリポジトリはあったのですがフレームワークを使わないgolang標準のやつがなかったので作りました

https://github.com/tddbc/go_gotest

**Comment by grimrose** [comment]
:+1:

**Comment by katzchang** [comment]
:+1:
