### ISSUE TITLE
gitterの開設について

### ISSUE THREAD

**Issue by grimrose** [tddbc/organizers#19]
元ツイートを発見したので、変更しました。

変更前のリンクはこちら -> https://twitter.com/KingBodyCar01/status/698131506875625472

<blockquote class="twitter-tweet" data-lang="ja"><p lang="ja" dir="ltr"><a href="https://twitter.com/hashtag/tddbc?src=hash">#tddbc</a> せっかく GitHub organization あるわけだし、 Gitter に tddbc/public とかで部屋たてて質問できるようにしたり、各種ライブラリ情報をたれ流せる場所にできればいいんじゃないかなとか思った</p>&mdash; 重機合体ポケットバリカンサー (@pocketberserker) <a href="https://twitter.com/pocketberserker/status/665894128836722688">2015, 11月 15</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

ご意見等ありましたら、お願いします。

**Comment by katzchang** [comment]
やるならslackに1票

**Comment by pocketberserker** [comment]
（issueと内容と全然関係なくて申し訳ないのですが）参照しているアカウント、私の発言をコピーしているスパムだと思われるので気を付けてください…。

**Comment by grimrose** [comment]
@pocketberserker ホントだ…ありがとうございます。

**Comment by twada** [comment]
@pocketberserker 俺が先日スパム報告したアカウントですね……

@katzchang 単一アプリ単一アカウントで複数のチームを扱うには slack より gitter の方が向いてそうと思うんですけどどうでしょう。主に iOS アプリの出来に関することなのだけど、 slack app は Switch Teams しなければならないので見落としやすく、通知したらしたで今度は饒舌になってしまう。

**Comment by shishi** [comment]
僕はどちらでもって感じだけどチャットツールの導入には賛成です

**Comment by pocketberserker** [comment]
GitHubアカウントさえあれば誰でも入れる、というわかりやすさがよさそうに思えるのでgitterに一票です。
あと履歴が残る/残らないという話もあるのかな？

**Comment by grimrose** [comment]
https://gitter.im/tddbc/public

作成されたのでcloseします。
