### ISSUE TITLE
スケルトンのライセンス

### ISSUE THREAD

**Issue by toshi-kawanishi** [tddbc/organizers#20]
スケルトンを追加する際に、ライセンスの方針などあるでしょうか。既存のスケルトンはリポジトリごとにバラバラなようでした。各言語やフレームワークの習わしに合わせる感じになるでしょうか。

**Comment by grimrose** [comment]
Google groupにそれらしい議論がありました。

https://groups.google.com/forum/#!searchin/tddbc/%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9/tddbc/kACf-MERL6Q/mbfe9DkcpKIJ

**Comment by toshi-kawanishi** [comment]
"具体的なライセンスの選択は各人に任せますが、同梱するライブラリに抵触しない何らかの OSS ライセンスを選び、明記する"

ということでまとまっている感じですね、ありがとうございます :bow:

**Comment by katzchang** [comment]
> * 何らかの OSS ライセンス (ASL/MIT 系, MPL 系,  GPL 系) を必ず明記する
> * ライセンス無しはNG。明記していないことに気づいた人はリポジトリ作成者に指摘する
> * 具体的なライセンスに何を使うかは各人にお任せ
> * （テスティングフレームワークなどの）ライブラリを同梱する場合、ライセンス違反になっていないか確認する

の部分ですね。

**Comment by pocketberserker** [comment]
これ、organizersのREADMEに書いておいてもいいかもしれませんねぇ

**Comment by katzchang** [comment]
ということで、READMEに記載しました。

**Comment by toshi-kawanishi** [comment]
:bow:
