### ISSUE TITLE
Doorkeeper から connpass への移行について

### ISSUE THREAD

**Issue by twada** [tddbc/organizers#24]
TDDBC は開催支援のインフラとして Doorkeeper を長らく使ってきましたが、今年 Doorkeeper の料金体系変更があり、細くゆるやかに継続することを目指すコミュニティにとっては少し厳しい出費となってしまうことがわかりました。
- [Doorkeeper料金体系の変更について | Doorkeeper](https://www.doorkeeper.jp/news/2016/7/25/change-in-pricing)
- [無料から有料サービスへ：有料化発表後のDoorkeeper | Doorkeeper](https://www.doorkeeper.jp/news/2016/8/22/from-free-to-paid-status-update)

このことを鑑み、 Doorkeeper と同等の機能を持つサービスを検討したところ、 [connpass](http://connpass.com/) が筆頭に挙がりました。
今後も低コストで細くゆるやかに継続するために、開催のインフラを connpass に移行していきたいと考えていますが、いかがでしょうか。

**Comment by shishi** [comment]
特に問題ないんじゃないかと思います

**Comment by grimrose** [comment]
connpassに移行する場合ですが、移行しましたという告知はいかがいたしますか？

**Comment by twada** [comment]
@grimrose ああー、なるほど。告知ですか。どうしようかな。
- そもそも告知が必要か (開催者以外にとっての TDDBC Doorkeeper 認知度や利用度はどれくらいか)
- 告知するとしたら、誰に、いつ、どんな手段で行うか

を考えたいです。まずは @grimrose さんご意見をお聞かせ願えればと！

**Comment by masaru-b-cl** [comment]
@twada @grimrose 
Doorkeeperのメッセージ機能は無料の範囲で使えるので、それ使えば過去に参加した人全員にメールを送ることはできるかと思います。

（完全に余談ですが、私が主催しているNiigata.NETもconnpassに移動して、メッセージ機能で告知しました

**Comment by grimrose** [comment]
@twada 直近の仙台のTAの確保や、過去参加した人が主催する機会を設けるという観点から告知してもいいのではないかと思います。

**Comment by twada** [comment]
@masaru-b-cl @grimrose ご意見、非常に参考になりました。ありがとうございます!
Doorkeeper のメッセージ機能で引越を告知するのがよさそうですね。

**Comment by twada** [comment]
ひとまず移行先の connpass group をつくりました! (まだつくっただけ)
[TDDBC - connpass](http://tddbc.connpass.com/)

**Comment by twada** [comment]
Doorkeeper からコミュニティの皆様へ connpass へ移行する旨のメール送信 Done.

**Comment by twada** [comment]
仙台と富山の開催を無事終えたので、この issue を close しますね。
