### ISSUE TITLE
Doorkeeper の運営ルールを確立する

### ISSUE THREAD

**Issue by twada** [tddbc/organizers#8]
東京開催に立候補してくださった藤原さんから下記のような質問を ML にいただきました。

https://groups.google.com/forum/?hl=ja&fromgroups=#!topic/tddbc/rtq1qSTZlhM

確かに、まだ使い始めて日も浅いので、運営ルールが無いですよね。

どうやっていきましょうか。立候補してくださった方に
- Doorkeeper 
- github organization

の管理権限を差し上げる、という形で良いでしょうか?

**Comment by pocketberserker** [comment]
#24 の話がまとまったらcloseする（connpassの運営ルールを決める必要があるとしても、別issue立てたほうが良いと思うので）

**Comment by pocketberserker** [comment]
#24 のcloseに伴い、このissueも閉じます。
